// taken from https://github.com/loujine/musicbrainz-scripts/blob/master/mbz-loujine-common.js
export const languageCodes = {
	'Afrikaans': 'af',
	'Azerbaijani': 'az',
	'Albanian': 'sq',
	'Arabic': 'ar',
	'Armenian': 'hy',
	'Bengali/Bangla': 'bn',
	'Basque': 'eu',
	'Belorussian': 'be',
	'Bosnian': 'bs',
	'Bulgarian': 'bg',
	'Cantonese': 'zh_yue',
	'Catalan': 'ca',
	'Chinese': 'zh',
	'Croatian': 'hr',
	'Czech': 'cs',
	'Danish': 'da',
	'Dutch': 'nl',
	'English': 'en',
	'Esperanto': 'eo',
	'Estonian': 'et',
	'Finnish': 'fi',
	'French': 'fr',
	'German': 'de',
	'Greek': 'el',
	'Hebrew': 'he',
	'Hindi': 'hi',
	'Hungarian': 'hu',
	'Icelandic': 'is',
	'Indonesian': 'id',
	'Irish': 'ga',
	'Italian': 'it',
	'Japanese': 'ja',
	'Javanese': 'jv',
	'Kazakh': 'kk',
	'Khmer (Central)': 'km',
	'Korean': 'ko',
	'Latvian': 'lv',
	'Lithuanian': 'lt',
	'Macedonian': 'mk',
	'Malay': 'ms',
	'Malayam': 'ml',
	'Nepali': 'ne',
	'Norwegian Bokmål': 'nb',
	'Norwegian Nynorsk': 'nn',
	'Persian (Farsi)': 'fa',
	'Polish': 'pl',
	'Portuguese': 'pt',
	'Punjabi': 'pa',
	'Romanian': 'ro',
	'Russian': 'ru',
	'Serbian': 'sr',
	'Serbo-Croatian': 'sh',
	'Slovakian': 'sk',
	'Slovenian': 'sl',
	'Spanish': 'es',
	'Swahili': 'sw',
	'Swedish': 'sv',
	'Thai': 'th',
	'Turkish': 'tr',
	'Urdu': 'ur',
	'Ukrainian': 'uk',
	'Uzbek': 'uz',
	'Vietnamese': 'vi',
	'Welsh (Cymric)': 'cy',
};

/**
 * Detects the selected language in the release editor.
 * @returns {string} Language as ISO 639-1 two letter code.
 */
export function detectReleaseLanguage() {
	const languageName = $('#language option:selected').text();
	return languageCodes[languageName];
}
